image: node:16

variables:
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn/cache

cache:
  key: install-cache
  paths:
    - .yarn/cache

before_script:
  - yarn install --immutable

stages:
  - build
  - test

build-job:
  stage: build
  parallel:
    matrix:
      - WORKSPACE: [bot, kernel]
  script:
    - yarn workspace $WORKSPACE run tsc --noEmit --skipLibCheck --strict

unit-test-job:
  stage: test
  needs: [build-job]
  parallel:
    matrix:
      - WORKSPACE: [bot, kernel]
  script:
    - yarn workspace $WORKSPACE run test

lint-test-job:
  stage: test
  needs: []
  parallel:
    matrix:
      - WORKSPACE: [bot, kernel]
  script:
    - yarn workspace $WORKSPACE run test
