image: node:16

cache:
  key: install-cache
  paths:
    - .yarn/cache

before_script:
  - yarn install --immutable

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  parallel:
    matrix:
      - WORKSPACE: [bot, kernel]
  script:
    - yarn workspace $WORKSPACE run tsc --noEmit --skipLibCheck --strict

unit-test-job:
  stage: test
  needs: [build-job]
  parallel:
    matrix:
      - WORKSPACE: [bot, kernel]
  script:
    - yarn workspace $WORKSPACE run test

lint-test-job:
  stage: test
  needs: []
  script:
    - yarn lint

deploy_mmo:
  stage: deploy
  script:
    - yarn deploy:mmo
  environment:
    name: MMO
    url: https://screeps.com/a/#!/profile/Jomik
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
