version: '3'
services:
  screeps:
    image: jomik/screeps-server:edge
    ports:
      - 21025:21025/tcp
    volumes:
      - ./server.config.yml:/screeps/config.yml
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
      STEAM_KEY: ${STEAM_KEY:?"Missing steam key"}
    restart: unless-stopped
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis
    volumes:
      - redis-data:/data
    restart: unless-stopped

  client:
    image: node:16
    working_dir: /home/root/client
    command: sh -c 'npm install --log-level=error --no-progress laverdet/screeps-steamless-client && npx screeps-steamless-client --package /screeps.nw --host 0.0.0.0 --internal_backend http://screeps:21025 --backend http://localhost:21025'
    environment:
      SCREEPS_NW_PATH: ${SCREEPS_NW_PATH:?"Missing screeps nw file"}
    volumes:
      - ${SCREEPS_NW_PATH}:/screeps.nw

    ports:
      - 8080:8080/tcp
    restart: unless-stopped

volumes:
  redis-data:
  mongo-data:
