version: '3'
services:
  screeps:
    image: jomik/screeps-server:latest-mongo
    depends_on:
      - mongo
      - redis
    ports:
      - 21025:21025/tcp
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
      STEAM_KEY: ${STEAM_KEY:?"Missing steam key"}
    restart: unless-stopped

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis
    volumes:
      - redis-data:/data
    restart: unless-stopped

  client:
    image: node:16
    user: node
    command: sh -c "mkdir -p /home/node/client && cd /home/node/client && npm init -y && npm install laverdet/screeps-steamless-client && ./node_modules/.bin/screeps-steamless-client --package /screeps.nw"
    environment:
      SCREEPS_NW_PATH: ${SCREEPS_NW_PATH:?"Missing screeps nw file"}
    volumes:
      - ${SCREEPS_NW_PATH}:/screeps.nw
    network_mode: host
    # ports:
    #   - 8080:8080/tcp
    restart: unless-stopped

volumes:
  redis-data:
  mongo-data:
