name: Continous delivery

on:
  push:
    branches:
      - main

jobs:
  integration:
    permissions:
      checks: write
    uses: ./.github/workflows/ci.yml
  deploy:
    needs: integration
    runs-on: ubuntu-latest
    environment:
      name: MMO
      url: https://screeps.com/a/#!/profile/Jomik
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: Deploy MMO
        run: yarn deploy:mmo
        env:
          SCREEPS_MMO_TOKEN: ${{ secrets.SCREEPS_TOKEN }}
