name: Continous integration

on:
  pull_request:
    branches:
      - 'main'
  workflow_call:

jobs:
  workspaces:
    uses: ./.github/workflows/workspaces.yml
  build:
    runs-on: ubuntu-latest
    needs: workspaces
    strategy:
      fail-fast: false
      matrix:
        workspace: ${{ fromJSON(needs.workspaces.outputs.workspaces) }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: 'typescript compile'
        run: yarn workspace ${{ matrix.workspace }} run tsc --noEmit --strict --skipLibCheck
  unit-test:
    runs-on: ubuntu-latest
    needs:
      - workspaces
      - build
    strategy:
      fail-fast: false
      matrix:
        workspace: ${{ fromJSON(needs.workspaces.outputs.workspaces) }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: 'run test'
        run: yarn workspace ${{ matrix.workspace }} run test --reporters="github-actions"
  coverage:
    runs-on: ubuntu-latest
    needs:
      - unit-test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: 51c7f30f122040979cda7714bfe59e47bd6ce27c2e157d40345d9fa07788ed6b
        with:
          coverageCommand: yarn workspaces foreach --no-private run test --coverage
          coverageLocations: |
            ${{github.workspace}}/packages/*/coverage/lcov.info:lcov
  lint:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: 'run lint'
        run: yarn lint
