name: Continous integration

on:
  pull_request:
    branches:
      - 'main'
  workflow_call:

jobs:
  workspaces:
    uses: ./.github/workflows/workspaces.yml
  build:
    runs-on: ubuntu-latest
    needs: workspaces
    strategy:
      fail-fast: false
      matrix:
        workspace: ${{ fromJSON(needs.workspaces.outputs.workspaces) }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: 'typescript compile'
        run: yarn workspace ${{ matrix.workspace }} run tsc --noEmit --strict --skipLibCheck
  unit-test:
    runs-on: ubuntu-latest
    needs:
      - workspaces
      - build
    strategy:
      fail-fast: false
      matrix:
        workspace: ${{ fromJSON(needs.workspaces.outputs.workspaces) }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: 'run test'
        run: yarn workspace ${{ matrix.workspace }} run test --reporters="github-actions"
  lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: 'run lint'
        run: yarn lint --output-file lint_report.json --format json
        continue-on-error: true
      - name: 'annotate'
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: 'lint_report.json'
