name: Workspaces

on:
  workflow_call:
    outputs:
      workspaces:
        value: ${{  jobs.workspaces.outputs.workspaces }}

jobs:
  workspaces:
    runs-on: ubuntu-latest
    outputs:
      workspaces: ${{ steps.output-workspaces.outputs.workspaces }}
    steps:
      - uses: actions/checkout@v3
      - name: output workspaces
        id: output-workspaces
        run: ls packages | jq -R -s -c 'split("\n")[:-1]' | sed -e 's/^/workspaces=/;' >> $GITHUB_OUTPUT
